version: '3'
services:
  redis:
    image: "arm32v7/redis"
    command: --appendonly yes --maxmemory 512mb --tcp-backlog 128
    restart: unless-stopped
  service:
    image: "vrince/rpi-ws281x-service"
    build:
      context: .
      dockerfile: service.dockerfile
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis
    restart: unless-stopped
  worker:
    image: "vrince/rpi-ws281x-worker"
    build:
      context: .
      dockerfile: worker.dockerfile
    environment:
      REDIS_URL: redis://redis
    restart: unless-stopped
    privileged: true